### ISSUE TITLE
Homebrew install on macOS 10.14.4 (command 'clang' failed with exit status 1)

### ISSUE THREAD

**Issue by markhdavis** [ArchiveTeam/grab-site#150]
I'm am getting this error, after which I'm dead in the water, unless I install another way. 

Help appreciated.

src/as-libxml.c:14:10: fatal error: 'libxml/tree.h' file not found
    #include <libxml/tree.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/blink/gs-venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/vl/bd9b0hh91rbdm13h_ssd3gw00000gy/T/pip-install-n7z0pkx8/html5-parser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/vl/bd9b0hh91rbdm13h_ssd3gw00000gy/T/pip-record-q2mw82qg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/blink/gs-venv/include/site/python3.7/html5-parser" failed with error code 1 in /private/var/folders/vl/bd9b0hh91rbdm13h_ssd3gw00000gy/T/pip-install-n7z0pkx8/html5-parser/

**Comment by ivan** [comment]
Thanks for the report, this should be fixed in the README now. Please let me know if it's still broken.
