### ISSUE TITLE
Crawl eventually becomes nothing but "Disconnected from ws:// server:"...

### ISSUE THREAD

**Issue by BradCoffield** [ArchiveTeam/grab-site#152]
Hi there,

I'm getting this command line output sometimes through the crawl and last night after letting a full crawl of our site go overnight I was getting just it. Though once I closed the process and inspected the warc it seemed to be in good shape...

`Disconnected from ws:// server: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 29000)")`

I have no idea what this means. Should I be adding that port to an ignore list? Thanks!

**Comment by ivan** [comment]
That's grab-site trying to connect to gs-server. It's harmless if grab-site fails to connect, though it is unexpected if gs-server is running.

**Comment by BradCoffield** [comment]
Interesting. Okay, thank you!
