### ISSUE TITLE
Possible to run in the cloud?

### ISSUE THREAD

**Issue by BradCoffield** [ArchiveTeam/grab-site#159]
Does anyone have any insights on the feasibility of setting up an instance of grab-site on a service like Heroku? I'd like to do so in order to take advantage of automating scrapes that I need to happen monthly and weekly. Also, would like to use cloud functions to listen and take the output and save the files to AWS.

I'm researching but it seems like maybe installing grab-site on Heroku isn't possible and I was hoping to get input before potentially wasting a bunch more time. Thanks!

**Comment by BradCoffield** [comment]
I've looked into it a bit more and I'm pretty sure that if it's possible it will require Docker.

**Comment by raspher** [comment]
Digging...

Currently working on Dockerfile for grab-site. Successfully compiled, needs a little enchancements and documentation (and ofc testing).

**Comment by brandongalbraith** [comment]
I've used this docker container before successfully: https://hub.docker.com/r/slang800/grab-site/

**Comment by raspher** [comment]
@brandongalbraith yes, it's based on it a little

**Comment by brandongalbraith** [comment]
@raspher Looking forward to your updated Dockerfile 😄

**Comment by raspher** [comment]
Python 3.8 cannot be used, cannot pass URL due to error "TypeError: required field "posonlyargs" missing from arguments" (python 3.8 only)

**Comment by raspher** [comment]
Beta version of dockerfile

`FROM python:3.7-alpine3.12
WORKDIR /app
RUN apk add --no-cache --update build-base libffi-dev libxml2-dev libxslt-dev re2-dev pkgconfig git libressl-dev musl-dev && \
    git clone --depth=1 --branch=master https://github.com/ArchiveTeam/grab-site.git && \
    cd grab-site && \
    pip3 install --upgrade pip setuptools && \
    pip3 install --no-binary lxml --upgrade ./ && \
    apk del --purge build-base libffi-dev pkgconfig git musl-dev && \
    rm -R /root/.cache
VOLUME ["/data"]
WORKDIR /data
EXPOSE 29000/tcp
CMD ["python", "/app/grab-site/gs-server"]`

**Comment by BradCoffield** [comment]
This is beautiful. Can't wait to try it all out!
