### ISSUE TITLE
--finished-warc-dir= not working for me

### ISSUE THREAD

**Issue by BradCoffield** [ArchiveTeam/grab-site#161]
I'm running grab-site from within a subfolder in my system. If I run it regular it will create a new folder inside the subfolder I'm working in. When I create a folder in advance and then pass that to --finished-warc-dir= I get an error that what I've specified isn't a directory....

Perhaps its a syntax issue on my end but I think I've tried every possible iteration of --finished-war-dir= (like, putting the directory name in quotes, not in quotes, adding forward slashes, etc)

**Comment by ivan** [comment]
`--finished-warc-dir=` should be an _absolute path_ to a directory that already exists. README needs an update to mention this, sorry. If an absolute path still does not work, can you provide your grab-site arguments and error output?

Using `--finished-warc-dir=` won't stop grab-site from creating a new directory for the crawl itself, though; it's just for finished `.warc.gz` and `.cdx` files.

**Comment by BradCoffield** [comment]
That did it! Thank you :)
