### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by x8185** [ArchiveTeam/grab-site#182]
Saw a pull request for this here https://github.com/ArchiveTeam/grab-site/pull/93 but there hasn't been a update for years

So are there any plans to officially ship a Dockerfile for this to simplify the installation and improve reliability?

Doing so would also make it more cross-platform.

**Comment by jtagcat** [comment]
Don't open up a duplicate issue please.

**Comment by ivan** [comment]
I don't use Docker and there hasn't been anyone else around to do the technical leadership necessary to get Docker support included and maintained here. This is not just about making a Docker container, but also fully documenting all the equivalent usage in the README, which would probably involve one container per grab-site. For cross-platform installation, I recommend installing grab-site from nixpkgs. This should work on any Linux and macOS (though more cumbersome).

**Comment by jtagcat** [comment]
Make a fork / start your own.

**Comment by acrois** [comment]
What I am developing here works: https://github.com/acrois/grab-site/tree/feature/dockerfile

**Comment by pirate** [comment]
is there any up-to-date Dockerfile available for this?
