### ISSUE TITLE
--no-offsite-links doesn't work

### ISSUE THREAD

**Issue by tripleo1** [ArchiveTeam/grab-site#183]

**Comment by ivan** [comment]
You might be seeing page requisites (images, CSS, etc) being grabbed rather than offsite links to a depth of one. Do you have a log or repro steps?

**Comment by tripleo1** [comment]
Does it do offsite links to a depth of one or none at all. This may be what is confusing me.

**Comment by TheTechRobo** [comment]
It shoudln't be doing offsite links at all. What you see is most likely, as ivan said, page requisites (such as stylesheets, photos, etc) are most likely what you're seeing

**Comment by ivan** [comment]
If this is still an issue, please post a log and all the arguments started grab-site with.
