### ISSUE TITLE
My computer crashed. I'm 10gb into a crawl. How can I "resume" this crawl? 

### ISSUE THREAD

**Issue by komali2** [ArchiveTeam/grab-site#185]
Partially through crawling a website, my computer crashed. I'd like to resume this crawl without re-downloading 10gb of information. How can I do so? 

My command was

`grab-site https://hk.appledaily.com/ --dir=/media/caleb/'bighdd'/appledaily3 --finished-warc-dir=/media/caleb/'bighdd'/appledaily`

If I try to run the same command again, I get the error `File exists: '/media/caleb/bighdd/appledaily3`.

**Comment by JustAnotherArchivist** [comment]
This is not currently supported: #58

**Comment by komali2** [comment]
Ok, thanks for letting me know, I will restart the archive!
