### ISSUE TITLE
Error while starting a crawl in docker container

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [ArchiveTeam/grab-site#196]
#### Description

After following readme instructions on acrois' fork I am able to see grab-site dashboard, I am able to get into the container using `docker exec -it gs-server sh`, but I can't start a crawl because of this error:

#### full log
```  
/data $ grab-site --concurrency 4 --delay 201-354 --no-video --finished-warc-dir ~/webcrawls --1 --level 4 --warc-max-size 3368709120 https://example.com
Traceback (most recent call last):
  File "/app/grab-site", line 4, in <module>
    main.main()
  File "/home/grab-site/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/grab-site/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/grab-site/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grab-site/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/libgrabsite/main.py", line 293, in main
    os.makedirs(working_dir)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/example.com-2021-08-07-1273d73d'```

**Comment by acrois** [comment]
Hi @Z2Up1UwcaYOyZq Please try without going into the container.
The preferred way to run applications on Docker is within separate containers.
So you must create one container for gs-server with the ports bound, then you create grab-site containers to crawl for you.

I have also updated the usage to be more concise, please make sure you are checked out to the latest version of the branch before trying the following steps:
```
docker build -t grab-site:latest .
docker network create -d bridge grab-network
docker run --net=grab-network --name=gs-server -d -p 29000:29000 --restart=unless-stopped grab-site:latest
docker run --net=grab-network --rm -d -e GRAB_SITE_HOST=gs-server -v ./data:/data:rw grab-site:latest grab-site https://www.example.com/
```

Note is an example on a Linux host, please adjust volume mounts if on Windows. Let me know how it goes, thank you for testing the branch.

**Comment by ivan** [comment]
Thanks for testing the PR!

I posted about the same problem in https://github.com/ArchiveTeam/grab-site/pull/195#issuecomment-907548409 and mentioned a workaround I'm using.

Closing this because I would like to keep feedback for the Docker PR on that PR.
