### ISSUE TITLE
Resuming a WARC after hard "No space left on device" error message?

### ISSUE THREAD

**Issue by Preservation-Quest** [ArchiveTeam/grab-site#210]
Ran out of space and although I understand how to download to a non-default directory, there isn't any information on resuming a mirror / WARC file.

**Comment by ivan** [comment]
It's not really supported yet - see #58

I recommend adapting and running https://github.com/ArchiveTeam/grab-site/blob/14c3bbdf7156a923c3b5baeef60b4e9fa3ef363c/extra_docs/pause_resume_grab_sites.sh in the background to pause grab-site processes when low on disk.
