### ISSUE TITLE
Update macOS install script to reflect current Python 3.9.x (rather than 3.7)

### ISSUE THREAD

**Issue by LeeBinder** [ArchiveTeam/grab-site#216]
```
brew update
brew install python@3.9 libxslt re2 pkg-config
/usr/local/opt/python@3.9/bin/python3 -m venv ~/gs-venv
PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig" ~/gs-venv/bin/pip install --no-binary lxml --upgrade git+https://github.com/ArchiveTeam/grab-site
```
👍

**Comment by TheTechRobo** [comment]
**grab-site does not work in Python 3.9**: https://github.com/ArchiveTeam/ludios_wpull/issues/20

**Comment by LeeBinder** [comment]
Hi @TheTechRobo - that's helpful to know. You have admin access here, don't you. How about if you add this info to the https://github.com/ArchiveTeam/grab-site#install-on-macos section? To add clarity that python 3.7 is actually required 👍.

**Comment by ivan** [comment]
Thanks, I have updated it to use python@3.8.

I considered adding a disclaimer just now, but people incorrectly mutate the install steps in many different ways and I don't really want to cover every possible thing in the README.

**Comment by TheTechRobo** [comment]
@LeeBinder I don't have admin access here.

**Comment by LeeBinder** [comment]
Fine - Ivan already updated the manual :)
