### ISSUE TITLE
No messege on Dashboard

### ISSUE THREAD

**Issue by CircleCrop** [ArchiveTeam/grab-site#219]
Manhole[1284:1651459414.5518]: Patched <built-in function fork> and <built-in function forkpty>.
Manhole[1284:1651459414.5530]: Manhole UDS path: /tmp/manhole-1284
Manhole[1284:1651459414.5537]: Waiting for new connection (in pid:1284) ...
/usr/local/lib/python3.8/dist-packages/wpull/protocol/http/client.py:185: UserWarning: HTTP session did not complete.
  warnings.warn(_('HTTP session did not complete.'))

python --version: 3.8.2
pip --version: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

pip list
Package                Version             
---------------------- --------------------
attrs                  20.2.0              
autobahn               22.3.2              
certifi                2019.11.28          
cffi                   1.15.0              
chardet                3.0.4               
click                  8.1.3               
cloud-init             19.1.6              
command-not-found      0.3                 
configobj              5.0.6               
cryptography           37.0.1              
dbus-python            1.2.16              
distro                 1.4.0               
distro-info            0.23ubuntu1         
dnspython              1.15.0              
dnspython3             1.15.0              
greenlet               1.1.2               
html5-parser           0.4.10              
html5lib               1.1                 
hyperlink              21.0.0              
idna                   2.8                 
Jinja2                 2.11.2              
jsonpatch              1.26                
jsonpointer            2.0                 
jsonschema             3.2.0               
language-selector      0.1                 
lxml                   4.8.0               
manhole                1.8.0               
MarkupSafe             1.1.1               
namedlist              1.8                 
netifaces              0.10.4              
oauthlib               3.1.0               
pip                    20.0.2              
psutil                 5.9.0               
pycparser              2.21                
PyGObject              3.36.0              
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyrsistent             0.17.3              
python-apt             2.0.0+ubuntu0.20.4.1
PyYAML                 5.3.1               
requests               2.24.0              
setuptools             45.2.0              
six                    1.15.0              
SQLAlchemy             1.3.24              
ssh-import-id          5.10                
tornado                4.5.3               
txaio                  22.2.1              
ubuntu-advantage-tools 20.3                
ufw                    0.36                
urllib3                1.25.8              
webencodings           0.5.1               
wheel                  0.34.2              
wpull                  3.0.9               
Yapsy                  1.12.2

**Comment by ivan** [comment]
How did you install grab-site? Note that I can only support the install steps listed in the README

**Comment by CircleCrop** [comment]
I installed grab-site on my Ubuntu 20.04 as a root user.
And then I installed the missing package through pip.

**Comment by ivan** [comment]
I recommend removing everything you've placed into `/usr/local/lib/python3.8` (and other Python leftovers in `/usr/local`) and not doing anything with pip as root. Then, follow https://github.com/ArchiveTeam/grab-site#install-on-ubuntu-1604-1804-2004-debian-9-stretch-debian-10-buster-debian-11-bullseye precisely and let me know if you still have problems. (i.e. post a full log of your install steps in a new issue.) I am unable to support arbitrarily wrong installations because Python will happily load in the wrong dependency versions and cause broken behavior.
