### ISSUE TITLE
Add upload option

### ISSUE THREAD

**Issue by upintheairsheep** [ArchiveTeam/grab-site#226]
Please add an uploader option that uses internetarchive to upload items after the crawl is complete or the storage is full? See https://archive.org/details/www.ccsdut.org-2022-04-26-3891bdff as an example crawl.

**Comment by TheTechRobo** [comment]
I don't think this is in scope.

**Comment by TheTechRobo** [comment]
Yeah, I feel like just using archivebot would be better for this kind of thing though, if you want to get it into the wayback machine at least.

**Comment by ivan** [comment]
https://gist.github.com/ivan/079530350ac94851d581b55b1d372440 may be useful. anyone is welcome to put it in its own repo
