### ISSUE TITLE
Allow starting crawls directly from the dashboard

### ISSUE THREAD

**Issue by brandongalbraith** [ArchiveTeam/grab-site#90]
Is this feasible?

**Comment by ivan** [comment]
It's feasible with some work.  There was a plan to implement this and more: https://gist.github.com/ivan/2caccf9fb1cdb8f3daea#file-grab-site-improvement-plan-L21 but I've had other priorities and haven't had much time with grab-site.

**Comment by brandongalbraith** [comment]
I have obviated the need for this by orchestrating launches of grab-site using a Docker container and k8s. If someone else feels the need for this exists still, please feel free to re-open or cut a new Issue.
